INSTALL_PREFIX = /usr/local

PROJECT_NAME = hashserver
PROJECT_DESCRIPTION = "A simple TCP server"
PROJECT_PREFIX = $$INSTALL_PREFIX/$$PROJECT_NAME

PROJECT_VERSION = $$cat(VERSION)
MAIN_VERSION = $$section(PROJECT_VERSION, ., 0, 2)
BUILD_VERSION = $$section(PROJECT_VERSION, ., 3, 3)

DEFINES *= APP_VERSION=\\\"$$PROJECT_VERSION\\\"
